import AppKit
import CryptoKit
import UniformTypeIdentifiers

/// Raw content captured from the clipboard or dropped on the notch, before it is saved.
enum ClipPayload: Sendable {
    case text(String)
    case link(URL, original: String)
    case image(Data)
    /// SVG copied as code (e.g. Figma's "Copy as SVG"): shown as a picture, pasted back as code.
    case svgCode(String)
    case files([URL])
    case color(String, hex: String)

    var kind: ClipKind {
        switch self {
        case .text: .text
        case .link: .link
        case .image, .svgCode: .image
        case .files: .file
        case .color: .color
        }
    }

    /// A stable fingerprint of the content, used to avoid duplicates.
    nonisolated var contentHash: String {
        let data: Data = switch self {
        case .text(let string): Data("t:\(string)".utf8)
        case .link(let url, _): Data("l:\(url.absoluteString)".utf8)
        case .image(let data): data
        case .svgCode(let code): Data(code.utf8)
        case .files(let urls): Data("f:\(urls.map(\.path).joined(separator: "\n"))".utf8)
        case .color(let string, _): Data("c:\(string)".utf8)
        }
        return SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}

/// Decides which category something belongs to.
enum ClipClassifier {

    // MARK: Pasteboard

    /// Types that password managers and other apps use to say "don't record this" (see nspasteboard.org).
    static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type"),
        .init("net.antelle.keeweb"),
    ]

    /// Password managers. Anything copied while one is in front is skipped, even if the app
    /// forgot to mark it (browser extensions can't be recognized this way: their source is the browser).
    static let ignoredApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop",
        "com.apple.Passwords", "com.apple.keychainaccess", "org.keepassxc.keepassxc",
        "com.lastpass.LastPass", "in.sinew.Enpass-Desktop", "com.markmcguill.strongbox.mac",
    ]

    static func shouldIgnore(_ pasteboard: NSPasteboard, from app: NSRunningApplication?) -> Bool {
        if let bundleID = app?.bundleIdentifier, ignoredApps.contains(bundleID) { return true }
        let types = Set(pasteboard.types ?? [])
        return !types.isDisjoint(with: ignoredTypes)
    }

    static func payload(from pasteboard: NSPasteboard) -> ClipPayload? {
        // 1. Files copied in Finder.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return payload(fromFiles: urls)
        }

        let string = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines)

        // 2. Images (screenshots, "Copy Image" in browsers). Apps like Excel or Keynote also put a
        // picture of the selection next to the text; in that case the text is what the user wants.
        if let imageData = imageData(from: pasteboard) {
            let textIsJustTheImageAddress = string.map { isSingleURL($0) } ?? true
            // An SVG always wins: design apps put its code next to it as text, which is the same drawing.
            if string?.isEmpty ?? true || textIsJustTheImageAddress || BlobStore.isSVG(imageData) {
                return .image(imageData)
            }
        }

        // 3. Text, links and colors.
        if let string, !string.isEmpty {
            return payload(fromString: string)
        }
        return nil
    }

    private static func imageData(from pasteboard: NSPasteboard) -> Data? {
        // SVG first: when an app offers both, the vector original beats a flattened copy.
        for type in [NSPasteboard.PasteboardType(UTType.svg.identifier), .png, .tiff,
                     .init(UTType.jpeg.identifier), .init(UTType.heic.identifier)] {
            if let data = pasteboard.data(forType: type) { return data }
        }
        return nil
    }

    // MARK: Files

    /// Image files bigger than this stay file references instead of being copied into Copa.
    static let maxImageFileSize = 200 * 1024 * 1024

    static func payload(fromFiles urls: [URL]) -> ClipPayload {
        // A single image file is filed under Images so it shows a real preview.
        if urls.count == 1, let url = urls.first,
           let type = UTType(filenameExtension: url.pathExtension), type.conforms(to: .image),
           let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize, size <= maxImageFileSize,
           let data = try? Data(contentsOf: url) {
            return .image(data)
        }
        return .files(urls)
    }

    // MARK: Strings

    static func payload(fromString raw: String) -> ClipPayload {
        let string = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        // SVG code (e.g. Figma's "Copy as SVG", or copied from a code editor) is a picture: show it as one.
        if isSVGMarkup(string) {
            return .svgCode(string)
        }
        if let hex = colorHex(from: string) {
            return .color(string, hex: hex)
        }
        if let url = linkURL(from: string) {
            return .link(url, original: string)
        }
        return .text(raw)
    }

    /// A complete SVG document: starts with `<svg` (optionally after an XML header or comment)
    /// and ends with `</svg>`.
    static func isSVGMarkup(_ string: String) -> Bool {
        guard string.utf8.count < 5_000_000, string.hasSuffix("</svg>") || string.lowercased().hasSuffix("</svg>") else { return false }
        let head = string.prefix(1024).lowercased()
        return (head.hasPrefix("<svg") || head.hasPrefix("<?xml") || head.hasPrefix("<!--")) && head.contains("<svg")
    }

    private static let linkDetector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue)

    static func isSingleURL(_ string: String) -> Bool { linkURL(from: string) != nil }

    /// Returns a URL only when the *whole* string is a single web address.
    static func linkURL(from string: String) -> URL? {
        guard !string.isEmpty, string.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              let detector = linkDetector else { return nil }
        let range = NSRange(string.startIndex..., in: string)
        guard let match = detector.firstMatch(in: string, range: range),
              match.range == range,
              let url = match.url,
              let scheme = url.scheme?.lowercased(),
              ["http", "https", "ftp"].contains(scheme) else { return nil }
        return url
    }

    // MARK: Colors

    /// Recognizes #RGB, #RGBA, #RRGGBB, #RRGGBBAA, rgb()/rgba() and hsl()/hsla().
    /// Returns an uppercase hex string such as "#0A84FF".
    static func colorHex(from string: String) -> String? {
        let s = string.lowercased()

        if let m = s.wholeMatch(of: #/#([0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})/#) {
            var digits = String(m.1)
            if digits.count <= 4 { digits = digits.map { "\($0)\($0)" }.joined() }
            return "#" + digits.uppercased()
        }

        if let m = s.wholeMatch(of: #/rgba?\(\s*(\d{1,3})[\s,]+(\d{1,3})[\s,]+(\d{1,3})\s*(?:[,\/]\s*([\d.]+%?))?\s*\)/#) {
            guard let r = Int(m.1), let g = Int(m.2), let b = Int(m.3), r <= 255, g <= 255, b <= 255 else { return nil }
            return hexString(r: Double(r) / 255, g: Double(g) / 255, b: Double(b) / 255, alpha: m.4.map { alphaValue(String($0)) })
        }

        if let m = s.wholeMatch(of: #/hsla?\(\s*([\d.]+)(?:deg)?[\s,]+([\d.]+)%[\s,]+([\d.]+)%\s*(?:[,\/]\s*([\d.]+%?))?\s*\)/#) {
            guard let h = Double(m.1), let sat = Double(m.2), let l = Double(m.3) else { return nil }
            let (r, g, b) = hslToRGB(h: h, s: sat / 100, l: l / 100)
            return hexString(r: r, g: g, b: b, alpha: m.4.map { alphaValue(String($0)) })
        }
        return nil
    }

    private static func alphaValue(_ string: String) -> Double {
        if string.hasSuffix("%") { return (Double(string.dropLast()) ?? 100) / 100 }
        return Double(string) ?? 1
    }

    private static func hexString(r: Double, g: Double, b: Double, alpha: Double?) -> String {
        func byte(_ v: Double) -> String { String(format: "%02X", Int((min(max(v, 0), 1) * 255).rounded())) }
        var hex = "#" + byte(r) + byte(g) + byte(b)
        if let alpha, alpha < 1 { hex += byte(alpha) }
        return hex
    }

    private static func hslToRGB(h: Double, s: Double, l: Double) -> (Double, Double, Double) {
        let c = (1 - abs(2 * l - 1)) * s
        let hp = h.truncatingRemainder(dividingBy: 360) / 60
        let x = c * (1 - abs(hp.truncatingRemainder(dividingBy: 2) - 1))
        let (r1, g1, b1): (Double, Double, Double) = switch hp {
        case 0..<1: (c, x, 0)
        case 1..<2: (x, c, 0)
        case 2..<3: (0, c, x)
        case 3..<4: (0, x, c)
        case 4..<5: (x, 0, c)
        default: (c, 0, x)
        }
        let m = l - c / 2
        return (r1 + m, g1 + m, b1 + m)
    }
}
